config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users,
             controllers: {
               invitations: 'users/invitations',
               sessions: 'users/sessions'
             },
             skip: [:registrations]

  root to: 'site/home#index'

  get 'about', to: 'site/about#index'

  namespace :admin do
    resources :organizations, only: [:edit, :index, :show, :update]
    resources :integrations, except: [:destroy]
    resources :users
  end
  resources :entities, only: [:index, :show]
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :invitable,
         :lockable,
         :recoverable,
         :rememberable,
         :trackable
  rolify
  validates :email, :name, presence: true
  validates :email, uniqueness: true

  def after_password_reset; end
end

app/controllers/admin/users_controller.rb
# Admin
module Admin
  # Controller for managing existing users
  class UsersController < ApplicationController
    using Decoration

    before_action -> { authorize :user }, except: [:show]
    before_action -> { authorize user }, only: [:show]
    before_action :decorate_user, only: [:show]

    helper_method :entry, :user, :users
    respond_to :html

    def create
      render :new and return unless entry.valid?

      handle_service_result(invite_user,
                            -> { redirect_to(admin_user_path(user)) },
                            -> { render :new })
    end

    def update
      render :edit and return unless entry.valid?

      handle_service_result(update_user,
                            -> { redirect_to(admin_user_path(user)) },
                            -> { render :edit })
    end

    protected

    def build_user
      User.new(user_params.except(:role_names))
    end

    def entry
      @entry ||= UserEntry
                 .new(user.attributes)
                 .merge_hash(user_params)
    end

    def decorate_user
      @user = user.decorate
    end

    def find_user
      User.find(params[:id])
    end

    def invite_user
      result = InviteUser.call(entry.to_h.merge(current_user: current_user))
      @user = result.user
      result
    end

    def update_user
      result = UpdateUser.call(
        entry.to_h.merge(id: user.id, current_user: current_user))
      @user = result.user
      result
    end

    def user
      @user ||= params[:id] ? find_user : build_user
    end

    def user_params
      params
        .require(:entry)
        .permit(:email, :name, :is_active, role_names: [])
    rescue ActionController::ParameterMissing; {}
    end

    def users
      @users ||= User.all.to_a.decorate_all
    end
  end
end

app/controllers/users/invitations_controller.rb
module Users
  class InvitationsController < Devise::InvitationsController
    before_action :build_accept_entry, only: [:edit, :update]
    prepend_before_filter :resource_from_invitation_token,
                          only: [:destroy, :edit, :update]

    def edit
      resource.invitation_token = params[:invitation_token]
      @entry.name = resource.name
      @entry.invitation_token = resource.invitation_token
    end

    # rubocop:disable Metrics/AbcSize
    def update
      return render :edit unless @entry.valid?

      result = AcceptUserInvite.call(@entry.to_h)

      self.resource = result.invited_user

      if result.success?
        if Devise.allow_insecure_sign_in_after_accept
          if resource.active_for_authentication?
            flash_message = :updated
          else
            flash_message = :updated_not_active
          end
          set_flash_message :notice, flash_message if is_flashing_format?
          sign_in(resource_name, resource)
          respond_with resource, location: after_accept_path_for(resource)
        else
          set_flash_message :notice, :updated_not_active if is_flashing_format?
          respond_with resource, location: new_session_path(resource_name)
        end
      else
        resource.invitation_token = invitation_token
        respond_with_navigational(resource) { render :edit }
      end
    end
    # rubocop:enable Metrics/AbcSize

    protected

    def build_accept_entry
      @entry = AcceptInviteEntry.new(accept_params)
    end

    def accept_params
      params
        .require(:entry)
        .permit(:name, :password, :password_confirmation, :invitation_token)
    rescue ActionController::ParameterMissing; {}
    end

    def find_resource_by_token
      resource_class.find_by_invitation_token(invitation_token, true)
    end

    def invitation_token
      params[:invitation_token] || accept_params[:invitation_token]
    end

    def resource_from_invitation_token
      unless invitation_token && self.resource = find_resource_by_token
        set_flash_message(:alert, :invitation_token_invalid) \
          if is_flashing_format?
        redirect_to after_sign_out_path_for(resource_name)
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'minimal'
end

app/views/admin/users/_form.html.erb
<%= error_messages model %>

<%= form.input :email, autofocus: true %>
<%= form.input :name %>
<%= form.input :role_names,
    collection: Role::ROLE_NAMES,
    label: 'Roles',
    input_html: { multiple: true } %>
<%= form.input :is_active,
               as: :boolean,
               boolean_style: :inline,
               wrapper: :horizontal_boolean %>

app/views/admin/users/edit.html.erb
<%= render :layout => '/heading',
           :locals => { :size => 'h2', :title => 'Edit User' } do %>
  <nav class="pull-right">
    <%= link_to 'Return to user',
                admin_user_path(@user),
                :class => 'btn btn-link' %>
  </nav>
<% end %>
<div>
  <%= simple_form_for(@user_entry,
                      :html => { :class => 'form-horizontal' },
                      :method => :patch,
                      :url => admin_user_path(@user),
                      :wrapper => :horizontal_form) do |form| %>
    <%= render :partial => 'form',
         :locals => { :form => form, :model => @user_entry } %>
    <div class="actions">
      <%= form.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<%= render :layout => '/heading',
           :locals => { :size => 'h2', :title => t('users.index.title') } do %>
  <nav class="pull-right">
    <%= link_to 'New', new_admin_user_path, class: 'btn btn-default' %>
  </nav>
<% end %>
<section>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>Last Signed In</th>
    </tr>
    </thead>
    <tbody>
    <% if users.each do |user| %>
      <tr>
          <td nowrap><%= link_to user.name, admin_user_path(user) %></td>
          <td nowrap><%= user.email %></td>
          <td nowrap><%= user.active_label %></td>
          <td nowrap><%= user.last_sign_in_at %></td>
      </tr>
    <% end.empty? %>
      <tr>
        <td colspan="4">No users found</td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/admin/users/new.html.erb
<%= render layout: '/heading',
           locals: {
             size: 'h2',
             title: 'New User'
           } do %>
  <nav class="pull-right">
    <%= link_to 'Return to users',
                admin_users_path,
                :class => 'btn btn-link' %>
  </nav>
<% end %>
<div>
  <%= simple_form_for(entry,
                      as: :entry,
                      html: { class: 'form-horizontal' },
                      method: :post,
                      url: admin_users_path,
                      wrapper: :horizontal_form) do |form| %>
    <%= render partial: 'form', locals: { form: form, model: entry } %>
    <div class="actions">
      <%= form.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<%= render :layout => '/heading',
           :locals => { :size => 'h2', :title => user.name } do %>
  <nav class="pull-right">
    <%= link_to 'Edit', edit_admin_user_path(user), :class => 'btn btn-link' %>
  </nav>
<% end %>
<div class="form form-horizontal">
  <div class="form-group">
    <label class="col-sm-3 control-label">Name</label>
    <p class="col-sm-6 form-control-static"><%= user.name %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Email</label>
    <p class="col-sm-6 form-control-static"><%= user.email %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Roles</label>
    <p class="col-sm-6 form-control-static"><%= user.role_labels %></p>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label">Active?</label>
    <p class="col-sm-6 form-control-static"><%= user.active_label %></p>
  </div>
</div>